VOICE_PHRASES: tuple[str, ...] = (
    "take off",
    "land",
    "follow me",
    "stop following",
    "stop",
    "flip",
    "flip forward",
    "flip back",
    "flip left",
    "flip right",
    "go up",
    "go down",
    "go left",
    "go right",
    "go forward",
    "go back",
    "come closer",
    "go away",
    "rotate left",
    "rotate right",
    "take photo",
    "take a photo",
    "gesture mode",
    "voice mode",
)

